### ISSUE TITLE
web example is broken

### ISSUE THREAD

**Issue by himanshuchawla009** [torusresearch/tss-client#61]
- Fix web example to work with local
- Add a example file to run with deployed servers
- Web example with prod servers should run in CI with local package (point to local path of tss-client rather thn released one)

**Comment by matthiasgeihs** [comment]
Not sure how to run the local example in CI, without having the server in the same repository. Maybe we wanna move this repository into `tss-server` as well? @lwin-kyaw

**Comment by metalurgical** [comment]
Hey.

This is purely for us being able to test changes to local servers easily and requires that we run servers in development mode (so that test-only routes are available).

I see there is a small problem with the markdown formatting in the readme, it should indicate that it is to be run from the example and look like this:
```
npm run clean && npm run build  && npm run serve:local 
```

This in itself will not work with CI due to the above and that will need to be done slightly differently. 

Adding CI is both a good suggestion and necessary.

I think we can close this and open a separate issue for CI, if this isn't already done.

**Comment by himanshuchawla009** [comment]
fixed in #62
